<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE actionMap [
	<!ELEMENT actionMap (namespaces, entry+)>
		<!ELEMENT namespaces (namespace+)>
			<!ELEMENT namespace EMPTY>
			<!ATTLIST namespace prefix CDATA #REQUIRED>
			<!ATTLIST namespace uri CDATA #REQUIRED>
		<!ELEMENT entry (matcher, action)>
			<!ELEMENT matcher EMPTY>
			<!ATTLIST matcher nodeName CDATA #REQUIRED>
			<!ATTLIST matcher type CDATA #REQUIRED>
			<!ELEMENT action (preInsert?, midInsert*, postInsert?)>
			<!ATTLIST action type CDATA #REQUIRED>
			<!ATTLIST action xsltResource CDATA #IMPLIED>
			<!ATTLIST action table CDATA #IMPLIED>
			<!ATTLIST action altXsltResource CDATA #IMPLIED>
			<!ATTLIST action altTagName CDATA #IMPLIED>
			<!ATTLIST action open CDATA #IMPLIED>
			<!ATTLIST action separators CDATA #IMPLIED>
			<!ATTLIST action close CDATA #IMPLIED>
			<!ATTLIST action preOpen CDATA #IMPLIED>
			<!ATTLIST action preSeparators CDATA #IMPLIED>
			<!ATTLIST action preClose CDATA #IMPLIED>
				<!ELEMENT preInsert ANY>
				<!ELEMENT midInsert ANY>
				<!ELEMENT postInsert ANY>

	<!ENTITY begin "&#xf401;">
	<!ENTITY end "&#xf402;">
	<!ENTITY separator "&#xf403;">
	<!ENTITY begin-math "&#xf32e;">
	<!ENTITY end-math "&#xf32f;">
	<!ENTITY begin-subscript "&begin;&#xf320;">
	<!ENTITY subscript-separator "&#xf320;">
	<!ENTITY end-subscript "&end;&#xf320;">
	<!ENTITY begin-superscript "&begin;&#xf321;">
	<!ENTITY superscript-separator "&#xf321;">
	<!ENTITY end-superscript "&end;&#xf321;">
	<!ENTITY begin-subsuperscript "&begin;&#xf320;">
	<!ENTITY end-subsuperscript "&end;&#xf321;">
	<!ENTITY begin-underscript "&begin;&#xf322;">
	<!ENTITY subsup-comma "&#xf3a0;">
	<!ENTITY underscript-separator "&#xf322;">
	<!ENTITY end-underscript "&end;&#xf322;">
	<!ENTITY begin-overscript "&begin;&#xf323;">
	<!ENTITY overscript-separator "&#xf323;">
	<!ENTITY end-overscript "&end;&#xf323;">
	<!ENTITY begin-underoverscript "&begin;&#xf322;">
	<!ENTITY end-underoverscript "&end;&#xf323;">
	<!ENTITY begin-expression "&#xf326;">
	<!ENTITY end-expression "&#xf327;">
	<!ENTITY begin-sqrt "&#xf32a;">
	<!ENTITY end-sqrt "&#xf32b;">
	<!ENTITY root-index "&#xf32c;">
	<!ENTITY begin-root "&#xf32a;">
	<!ENTITY root-separator "&separator;&begin-root;">
	<!ENTITY end-root "&#xf32b;">
	<!ENTITY begin-table "&#xf330;">
	<!ENTITY end-table "&#xf331;">
	<!ENTITY begin-row "&#xf332;">
	<!ENTITY end-row "&#xf333;">
	<!ENTITY begin-cell "&#xf334;">
	<!ENTITY end-cell "&#xf335;">

	<!ENTITY begin-fraction "&#xf500;">
	<!ENTITY fraction-separator "&#xf501;">
	<!ENTITY fraction-separator-bevelled "&#xf502;">
	<!ENTITY end-fraction "&#xf503;">

	<!ENTITY begin-mixed-fraction "&#xf504;">
	<!ENTITY mixed-fraction-separator "&#xf505;">
	<!ENTITY mixed-fraction-separator-bevelled "&#xf506;">
	<!ENTITY end-mixed-fraction "&#xf507;">

	<!ENTITY begin-complex-fraction "&#xf508;">
	<!ENTITY complex-fraction-separator "&#xf509;">
	<!ENTITY complex-fraction-separator-bevelled "&#xf50a;">
	<!ENTITY end-complex-fraction "&#xf50b;">

	<!ENTITY begin-simple-fraction "&#xf50c;">
	<!ENTITY simple-fraction-separator "&#xf50d;">
	<!ENTITY simple-fraction-separator-bevelled "&#xf50e;">
	<!ENTITY end-simple-fraction "&#xf50f;">
]>
<actionMap>
	<namespaces>
		<namespace prefix="dsy" uri="http://www.daisy.org/z3986/2005/dtbook/" />
		<namespace prefix="utd" uri="http://brailleblaster.org/ns/utd" />
		<namespace prefix="m" uri="http://www.w3.org/1998/Math/MathML" />
	</namespaces>
  <!--   MathML   -->
    <entry>
        <matcher nodeName="math" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <!-- <action type="org.brailleblaster.utd.mathactions.MathAction" preInsert="&begin-math;" postInsert="&end-math;"/> -->
        <action type="org.brailleblaster.utd.actions.XsltAction" xsltResource="/org/brailleblaster/utd/xslt/mathml.xsl" table="MATH" altTagName="alttext" altXsltResource="/org/brailleblaster/utd/xslt/MathML2AsciiMath.xsl"/>
    </entry>

    <!--   MathML tokens   -->
    <!--
    <entry>
        <matcher nodeName="mi" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.actions.ChangeTableTypeAction" table="MATH"/>
    </entry>
    <entry>
        <matcher nodeName="mn" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.actions.ChangeTableTypeAction" table="MATH"/>
    </entry>
     -->

	<entry>
		<matcher nodeName="mo" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
		<action type="org.brailleblaster.utd.mathactions.MoAction"/>
	</entry>

    <!--   MathML layout schemata   -->
    <entry>
        <matcher nodeName="mfenced" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.mathactions.InsertAttributeAction" open="open" close="close" separators="separators" preOpen="&begin;" preSeparators="&separator;" preClose="&end;"/>
    </entry>
    <entry>
        <matcher nodeName="mfrac" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.mathactions.InsertAction">
            <preInsert>&begin-fraction;</preInsert>
            <midInsert>&fraction-separator;</midInsert>
            <postInsert>&end-fraction;</postInsert>
        </action>
    </entry>
    <entry>
        <matcher nodeName="msub" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.mathactions.MSubSupAction">
            <preInsert>&begin-subscript;</preInsert>
            <midInsert>&subscript-separator;</midInsert>
            <postInsert>&end-subscript;</postInsert>
        </action>
    </entry>
    <entry>
        <matcher nodeName="msup" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.mathactions.MSubSupAction">
            <preInsert>&begin-superscript;</preInsert>
            <midInsert>&superscript-separator;</midInsert>
            <postInsert>&end-superscript;</postInsert>
        </action>
    </entry>
    <entry>
        <matcher nodeName="msubsup" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.mathactions.MSubSupAction">
            <preInsert>&begin-subsuperscript;</preInsert>
            <midInsert>&subscript-separator;</midInsert>
            <midInsert>&superscript-separator;</midInsert>
            <postInsert>&end-subsuperscript;</postInsert>
        </action>
    </entry>
    <!--  Nemeth.sem has msupsup but cannot find this mentioned in MathML reference. -->
    <entry>
        <matcher nodeName="munder" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.mathactions.InsertAction">
            <preInsert>&begin-underscript;</preInsert>
            <midInsert>&underscript-separator;</midInsert>
            <postInsert>&end-underscript;</postInsert>
        </action>
    </entry>
    <entry>
        <matcher nodeName="mover" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.mathactions.InsertAction">
            <preInsert>&begin-overscript;</preInsert>
            <midInsert>&overscript-separator;</midInsert>
            <postInsert>&end-overscript;</postInsert>
        </action>
    </entry>
    <entry>
        <matcher nodeName="munderover" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.mathactions.InsertAction">
            <preInsert>&begin-underoverscript;</preInsert>
            <midInsert>&underscript-separator;</midInsert>
            <midInsert>&overscript-separator;</midInsert>
            <postInsert>&end-underoverscript;</postInsert>
        </action>
    </entry>
    <entry>
        <matcher nodeName="mrow" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.mathactions.InsertAction">
            <preInsert>&begin-expression;</preInsert>
            <postInsert>&end-expression;</postInsert>
        </action>
    </entry>
    <entry>
        <matcher nodeName="msqrt" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.mathactions.InsertAction">
            <preInsert>&begin-sqrt;</preInsert>
            <postInsert>&end-sqrt;</postInsert>
        </action>
    </entry>
    <entry>
        <matcher nodeName="mroot" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.mathactions.ReverseAction">
            <preInsert>&root-index;</preInsert>
            <midInsert>&root-separator;</midInsert>
            <postInsert>&end-root;</postInsert>
        </action>
    </entry>
    <entry>
        <matcher nodeName="mtable" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
	    <action type="org.brailleblaster.utd.mathactions.MTableAction">
            <preInsert>&begin-table;</preInsert>
            <postInsert>&end-table;</postInsert>
        </action>
    </entry>
    <entry>
        <matcher nodeName="mtr" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
	    <action type="org.brailleblaster.utd.mathactions.MRowAction">
            <preInsert>&begin-row;</preInsert>
            <postInsert>&end-row;</postInsert>
        </action>
    </entry>
    <entry>
        <matcher nodeName="mtd" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.mathactions.InsertAction">
            <preInsert>&begin-cell;</preInsert>
            <postInsert>&end-cell;</postInsert>
        </action>
    </entry>
    <entry>
        <matcher nodeName="merror" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.actions.SkipAction"/>
    </entry>
    <entry>
        <matcher nodeName="mphantum" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.actions.SkipAction"/>
    </entry>
    <entry>
        <matcher nodeName="annotation" type="org.brailleblaster.utd.matchers.NodeNameMatcher"/>
        <action type="org.brailleblaster.utd.actions.SkipAction"/>
    </entry>
</actionMap>
